// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package view

import (
	model "laz/internal/model"
	"time"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ToAccount(source model.Account) Account {
	var viewAccount Account
	viewAccount.ID = source.ID
	viewAccount.Username = source.Username
	viewAccount.DisplayName = source.DisplayName
	viewAccount.Status = c.modelStatusToModelStatus(source.Status)
	viewAccount.Note = source.Note
	viewAccount.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewAccount.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewAccount
}
func (c *ConverterImpl) ToClient(source model.Client) Client {
	var viewClient Client
	viewClient.ID = source.ID
	viewClient.AccountID = source.AccountID
	viewClient.Slug = source.Slug
	viewClient.Name = source.Name
	viewClient.Status = source.Status
	viewClient.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewClient.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewClient
}
func (c *ConverterImpl) ToConfigProfile(source model.ConfigProfile) ConfigProfile {
	var viewConfigProfile ConfigProfile
	viewConfigProfile.ID = source.ID
	viewConfigProfile.Protocol = source.Protocol
	viewConfigProfile.Kind = source.Kind
	viewConfigProfile.Slug = source.Slug
	viewConfigProfile.Name = source.Name
	viewConfigProfile.Client = source.Client
	viewConfigProfile.ContentType = source.ContentType
	viewConfigProfile.Status = source.Status
	viewConfigProfile.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewConfigProfile.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewConfigProfile
}
func (c *ConverterImpl) ToConnection(source model.Connection) Connection {
	var viewConnection Connection
	viewConnection.ID = source.ID
	viewConnection.AccountID = source.AccountID
	viewConnection.ClientID = source.ClientID
	viewConnection.NodeID = source.NodeID
	viewConnection.Protocol = source.Protocol
	viewConnection.Status = c.modelStatusToModelStatus(source.Status)
	viewConnection.DesiredStatus = c.modelStatusToModelStatus(source.DesiredStatus)
	viewConnection.LastSyncAt = c.timeTimeToTimeTime(source.LastSyncAt)
	viewConnection.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewConnection.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewConnection
}
func (c *ConverterImpl) ToConnectionSummary(source model.ConnectionSummary) ConnectionSummary {
	var viewConnectionSummary ConnectionSummary
	viewConnectionSummary.Connection = c.ToConnection(source.Connection)
	viewConnectionSummary.Node = c.ToNode(source.Node)
	viewConnectionSummary.Client = c.ToClient(source.Client)
	return viewConnectionSummary
}
func (c *ConverterImpl) ToIssuedConfig(source model.IssuedConfig) IssuedConfig {
	var viewIssuedConfig IssuedConfig
	viewIssuedConfig.ID = source.ID
	viewIssuedConfig.ConnectionID = source.ConnectionID
	viewIssuedConfig.Kind = source.Kind
	viewIssuedConfig.Slug = source.Slug
	viewIssuedConfig.Name = source.Name
	viewIssuedConfig.Client = source.Client
	viewIssuedConfig.ContentType = source.ContentType
	viewIssuedConfig.Config = source.Config
	viewIssuedConfig.Status = c.modelStatusToModelStatus(source.Status)
	viewIssuedConfig.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewIssuedConfig.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewIssuedConfig
}
func (c *ConverterImpl) ToNode(source model.Node) Node {
	var viewNode Node
	viewNode.ID = source.ID
	viewNode.Name = source.Name
	viewNode.Type = source.Type
	viewNode.Region = source.Region
	viewNode.Status = c.modelStatusToModelStatus(source.Status)
	viewNode.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewNode.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewNode
}
func (c *ConverterImpl) ToSession(source model.ClientSession) Session {
	var viewSession Session
	viewSession.ID = source.ID
	viewSession.AccountID = source.AccountID
	viewSession.Status = c.modelStatusToModelStatus(source.Status)
	viewSession.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	viewSession.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	viewSession.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	viewSession.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return viewSession
}
func (c *ConverterImpl) modelStatusToModelStatus(source model.Status) model.Status {
	return source
}
func (c *ConverterImpl) timeTimeToTimeTime(source time.Time) time.Time {
	return source
}
