// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/agentcontrol.proto

package nodeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthManifestRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NodeId                 string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SinceManifestStartedAt int64                  `protobuf:"varint,2,opt,name=since_manifest_started_at,json=sinceManifestStartedAt,proto3" json:"since_manifest_started_at,omitempty"`
	Full                   bool                   `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthManifestRequest) Reset() {
	*x = AuthManifestRequest{}
	mi := &file_proto_agentcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthManifestRequest) ProtoMessage() {}

func (x *AuthManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthManifestRequest.ProtoReflect.Descriptor instead.
func (*AuthManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *AuthManifestRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthManifestRequest) GetSinceManifestStartedAt() int64 {
	if x != nil {
		return x.SinceManifestStartedAt
	}
	return 0
}

func (x *AuthManifestRequest) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type AuthManifestResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ManifestStartedAt int64                  `protobuf:"varint,2,opt,name=manifest_started_at,json=manifestStartedAt,proto3" json:"manifest_started_at,omitempty"`
	Full              bool                   `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	Users             []string               `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthManifestResponse) Reset() {
	*x = AuthManifestResponse{}
	mi := &file_proto_agentcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthManifestResponse) ProtoMessage() {}

func (x *AuthManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthManifestResponse.ProtoReflect.Descriptor instead.
func (*AuthManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *AuthManifestResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthManifestResponse) GetManifestStartedAt() int64 {
	if x != nil {
		return x.ManifestStartedAt
	}
	return 0
}

func (x *AuthManifestResponse) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *AuthManifestResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserAuthSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Users         []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthSnapshotRequest) Reset() {
	*x = UserAuthSnapshotRequest{}
	mi := &file_proto_agentcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthSnapshotRequest) ProtoMessage() {}

func (x *UserAuthSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UserAuthSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthSnapshotRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UserAuthSnapshotRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserAuthSnapshot struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	UserId                    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Op                        string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	CredentialId              string                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Username                  string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash              string                 `protobuf:"bytes,5,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	ExpiresAtMs               int64                  `protobuf:"varint,6,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	QuotaLimitBytes           int64                  `protobuf:"varint,7,opt,name=quota_limit_bytes,json=quotaLimitBytes,proto3" json:"quota_limit_bytes,omitempty"`
	LastKnownGlobalUsageBytes int64                  `protobuf:"varint,8,opt,name=last_known_global_usage_bytes,json=lastKnownGlobalUsageBytes,proto3" json:"last_known_global_usage_bytes,omitempty"`
	QuotaGuardOverageBytes    int64                  `protobuf:"varint,9,opt,name=quota_guard_overage_bytes,json=quotaGuardOverageBytes,proto3" json:"quota_guard_overage_bytes,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UserAuthSnapshot) Reset() {
	*x = UserAuthSnapshot{}
	mi := &file_proto_agentcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthSnapshot) ProtoMessage() {}

func (x *UserAuthSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthSnapshot.ProtoReflect.Descriptor instead.
func (*UserAuthSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *UserAuthSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAuthSnapshot) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UserAuthSnapshot) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *UserAuthSnapshot) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAuthSnapshot) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserAuthSnapshot) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *UserAuthSnapshot) GetQuotaLimitBytes() int64 {
	if x != nil {
		return x.QuotaLimitBytes
	}
	return 0
}

func (x *UserAuthSnapshot) GetLastKnownGlobalUsageBytes() int64 {
	if x != nil {
		return x.LastKnownGlobalUsageBytes
	}
	return 0
}

func (x *UserAuthSnapshot) GetQuotaGuardOverageBytes() int64 {
	if x != nil {
		return x.QuotaGuardOverageBytes
	}
	return 0
}

type UserAuthSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Snapshots     []*UserAuthSnapshot    `protobuf:"bytes,2,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthSnapshotResponse) Reset() {
	*x = UserAuthSnapshotResponse{}
	mi := &file_proto_agentcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthSnapshotResponse) ProtoMessage() {}

func (x *UserAuthSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UserAuthSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *UserAuthSnapshotResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UserAuthSnapshotResponse) GetSnapshots() []*UserAuthSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type UsageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FromMs        int64                  `protobuf:"varint,3,opt,name=from_ms,json=fromMs,proto3" json:"from_ms,omitempty"`
	ToMs          int64                  `protobuf:"varint,4,opt,name=to_ms,json=toMs,proto3" json:"to_ms,omitempty"`
	Records       []*UsageRecord         `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageBatch) Reset() {
	*x = UsageBatch{}
	mi := &file_proto_agentcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageBatch) ProtoMessage() {}

func (x *UsageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageBatch.ProtoReflect.Descriptor instead.
func (*UsageBatch) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *UsageBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *UsageBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UsageBatch) GetFromMs() int64 {
	if x != nil {
		return x.FromMs
	}
	return 0
}

func (x *UsageBatch) GetToMs() int64 {
	if x != nil {
		return x.ToMs
	}
	return 0
}

func (x *UsageBatch) GetRecords() []*UsageRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type UsageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	TxBytes       int64                  `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       int64                  `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRecord) Reset() {
	*x = UsageRecord{}
	mi := &file_proto_agentcontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRecord) ProtoMessage() {}

func (x *UsageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRecord.ProtoReflect.Descriptor instead.
func (*UsageRecord) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{6}
}

func (x *UsageRecord) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *UsageRecord) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *UsageRecord) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type UsageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageAck) Reset() {
	*x = UsageAck{}
	mi := &file_proto_agentcontrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageAck) ProtoMessage() {}

func (x *UsageAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageAck.ProtoReflect.Descriptor instead.
func (*UsageAck) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{7}
}

func (x *UsageAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *UsageAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Heartbeat struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	NodeId                     string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion               string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion            string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	HysteriaServiceStatus      string                 `protobuf:"bytes,4,opt,name=hysteria_service_status,json=hysteriaServiceStatus,proto3" json:"hysteria_service_status,omitempty"`
	LastTrafficCollectionMs    int64                  `protobuf:"varint,5,opt,name=last_traffic_collection_ms,json=lastTrafficCollectionMs,proto3" json:"last_traffic_collection_ms,omitempty"`
	LastOnlineCollectionMs     int64                  `protobuf:"varint,6,opt,name=last_online_collection_ms,json=lastOnlineCollectionMs,proto3" json:"last_online_collection_ms,omitempty"`
	PendingUsageBatchCount     int32                  `protobuf:"varint,7,opt,name=pending_usage_batch_count,json=pendingUsageBatchCount,proto3" json:"pending_usage_batch_count,omitempty"`
	PendingUsageQueueSizeBytes int64                  `protobuf:"varint,8,opt,name=pending_usage_queue_size_bytes,json=pendingUsageQueueSizeBytes,proto3" json:"pending_usage_queue_size_bytes,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agentcontrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Heartbeat) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Heartbeat) GetHysteriaServiceStatus() string {
	if x != nil {
		return x.HysteriaServiceStatus
	}
	return ""
}

func (x *Heartbeat) GetLastTrafficCollectionMs() int64 {
	if x != nil {
		return x.LastTrafficCollectionMs
	}
	return 0
}

func (x *Heartbeat) GetLastOnlineCollectionMs() int64 {
	if x != nil {
		return x.LastOnlineCollectionMs
	}
	return 0
}

func (x *Heartbeat) GetPendingUsageBatchCount() int32 {
	if x != nil {
		return x.PendingUsageBatchCount
	}
	return 0
}

func (x *Heartbeat) GetPendingUsageQueueSizeBytes() int64 {
	if x != nil {
		return x.PendingUsageQueueSizeBytes
	}
	return 0
}

type OnlineReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AtMs          int64                  `protobuf:"varint,2,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	Clients       []*OnlineClient        `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineReport) Reset() {
	*x = OnlineReport{}
	mi := &file_proto_agentcontrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReport) ProtoMessage() {}

func (x *OnlineReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReport.ProtoReflect.Descriptor instead.
func (*OnlineReport) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{9}
}

func (x *OnlineReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *OnlineReport) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *OnlineReport) GetClients() []*OnlineClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

type OnlineClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineClient) Reset() {
	*x = OnlineClient{}
	mi := &file_proto_agentcontrol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClient) ProtoMessage() {}

func (x *OnlineClient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClient.ProtoReflect.Descriptor instead.
func (*OnlineClient) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{10}
}

func (x *OnlineClient) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *OnlineClient) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RuntimeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IssuedMs      int64                  `protobuf:"varint,3,opt,name=issued_ms,json=issuedMs,proto3" json:"issued_ms,omitempty"`
	ExpiresMs     int64                  `protobuf:"varint,4,opt,name=expires_ms,json=expiresMs,proto3" json:"expires_ms,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeCommand) Reset() {
	*x = RuntimeCommand{}
	mi := &file_proto_agentcontrol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCommand) ProtoMessage() {}

func (x *RuntimeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCommand.ProtoReflect.Descriptor instead.
func (*RuntimeCommand) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{11}
}

func (x *RuntimeCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeCommand) GetIssuedMs() int64 {
	if x != nil {
		return x.IssuedMs
	}
	return 0
}

func (x *RuntimeCommand) GetExpiresMs() int64 {
	if x != nil {
		return x.ExpiresMs
	}
	return 0
}

func (x *RuntimeCommand) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RuntimeCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeCommandResult) Reset() {
	*x = RuntimeCommandResult{}
	mi := &file_proto_agentcontrol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCommandResult) ProtoMessage() {}

func (x *RuntimeCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCommandResult.ProtoReflect.Descriptor instead.
func (*RuntimeCommandResult) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{12}
}

func (x *RuntimeCommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RuntimeCommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuntimeCommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeCommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AgentHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_proto_agentcontrol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{13}
}

func (x *AgentHello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type AgentMessage struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	Type                    string                   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	RequestId               string                   `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Hello                   *AgentHello              `protobuf:"bytes,3,opt,name=hello,proto3" json:"hello,omitempty"`
	Heartbeat               *Heartbeat               `protobuf:"bytes,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	OnlineReport            *OnlineReport            `protobuf:"bytes,5,opt,name=online_report,json=onlineReport,proto3" json:"online_report,omitempty"`
	UsageBatch              *UsageBatch              `protobuf:"bytes,6,opt,name=usage_batch,json=usageBatch,proto3" json:"usage_batch,omitempty"`
	RuntimeCommandResult    *RuntimeCommandResult    `protobuf:"bytes,7,opt,name=runtime_command_result,json=runtimeCommandResult,proto3" json:"runtime_command_result,omitempty"`
	AuthRefreshResult       *AuthRefreshResult       `protobuf:"bytes,8,opt,name=auth_refresh_result,json=authRefreshResult,proto3" json:"auth_refresh_result,omitempty"`
	AuthManifestRequest     *AuthManifestRequest     `protobuf:"bytes,9,opt,name=auth_manifest_request,json=authManifestRequest,proto3" json:"auth_manifest_request,omitempty"`
	UserAuthSnapshotRequest *UserAuthSnapshotRequest `protobuf:"bytes,10,opt,name=user_auth_snapshot_request,json=userAuthSnapshotRequest,proto3" json:"user_auth_snapshot_request,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agentcontrol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{14}
}

func (x *AgentMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *AgentMessage) GetOnlineReport() *OnlineReport {
	if x != nil {
		return x.OnlineReport
	}
	return nil
}

func (x *AgentMessage) GetUsageBatch() *UsageBatch {
	if x != nil {
		return x.UsageBatch
	}
	return nil
}

func (x *AgentMessage) GetRuntimeCommandResult() *RuntimeCommandResult {
	if x != nil {
		return x.RuntimeCommandResult
	}
	return nil
}

func (x *AgentMessage) GetAuthRefreshResult() *AuthRefreshResult {
	if x != nil {
		return x.AuthRefreshResult
	}
	return nil
}

func (x *AgentMessage) GetAuthManifestRequest() *AuthManifestRequest {
	if x != nil {
		return x.AuthManifestRequest
	}
	return nil
}

func (x *AgentMessage) GetUserAuthSnapshotRequest() *UserAuthSnapshotRequest {
	if x != nil {
		return x.UserAuthSnapshotRequest
	}
	return nil
}

type ServerMessage struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	Type                     string                    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	RequestId                string                    `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AuthRefresh              *AuthRefresh              `protobuf:"bytes,3,opt,name=auth_refresh,json=authRefresh,proto3" json:"auth_refresh,omitempty"`
	RuntimeCommand           *RuntimeCommand           `protobuf:"bytes,4,opt,name=runtime_command,json=runtimeCommand,proto3" json:"runtime_command,omitempty"`
	UsageAck                 *UsageAck                 `protobuf:"bytes,5,opt,name=usage_ack,json=usageAck,proto3" json:"usage_ack,omitempty"`
	AuthManifestResponse     *AuthManifestResponse     `protobuf:"bytes,6,opt,name=auth_manifest_response,json=authManifestResponse,proto3" json:"auth_manifest_response,omitempty"`
	UserAuthSnapshotResponse *UserAuthSnapshotResponse `protobuf:"bytes,7,opt,name=user_auth_snapshot_response,json=userAuthSnapshotResponse,proto3" json:"user_auth_snapshot_response,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_agentcontrol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{15}
}

func (x *ServerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetAuthRefresh() *AuthRefresh {
	if x != nil {
		return x.AuthRefresh
	}
	return nil
}

func (x *ServerMessage) GetRuntimeCommand() *RuntimeCommand {
	if x != nil {
		return x.RuntimeCommand
	}
	return nil
}

func (x *ServerMessage) GetUsageAck() *UsageAck {
	if x != nil {
		return x.UsageAck
	}
	return nil
}

func (x *ServerMessage) GetAuthManifestResponse() *AuthManifestResponse {
	if x != nil {
		return x.AuthManifestResponse
	}
	return nil
}

func (x *ServerMessage) GetUserAuthSnapshotResponse() *UserAuthSnapshotResponse {
	if x != nil {
		return x.UserAuthSnapshotResponse
	}
	return nil
}

type AuthRefresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefresh) Reset() {
	*x = AuthRefresh{}
	mi := &file_proto_agentcontrol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefresh) ProtoMessage() {}

func (x *AuthRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefresh.ProtoReflect.Descriptor instead.
func (*AuthRefresh) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{16}
}

func (x *AuthRefresh) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthRefresh) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuthRefresh) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type AuthRefreshResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefreshResult) Reset() {
	*x = AuthRefreshResult{}
	mi := &file_proto_agentcontrol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefreshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshResult) ProtoMessage() {}

func (x *AuthRefreshResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentcontrol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshResult.ProtoReflect.Descriptor instead.
func (*AuthRefreshResult) Descriptor() ([]byte, []int) {
	return file_proto_agentcontrol_proto_rawDescGZIP(), []int{17}
}

func (x *AuthRefreshResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthRefreshResult) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuthRefreshResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthRefreshResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthRefreshResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_agentcontrol_proto protoreflect.FileDescriptor

const file_proto_agentcontrol_proto_rawDesc = "" +
	"\n" +
	"\x18proto/agentcontrol.proto\x12\rlaz.nodeproto\"}\n" +
	"\x13AuthManifestRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\x19since_manifest_started_at\x18\x02 \x01(\x03R\x16sinceManifestStartedAt\x12\x12\n" +
	"\x04full\x18\x03 \x01(\bR\x04full\"\x89\x01\n" +
	"\x14AuthManifestResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13manifest_started_at\x18\x02 \x01(\x03R\x11manifestStartedAt\x12\x12\n" +
	"\x04full\x18\x03 \x01(\bR\x04full\x12\x14\n" +
	"\x05users\x18\x04 \x03(\tR\x05users\"H\n" +
	"\x17UserAuthSnapshotRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\"\xee\x02\n" +
	"\x10UserAuthSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x05 \x01(\tR\fpasswordHash\x12\"\n" +
	"\rexpires_at_ms\x18\x06 \x01(\x03R\vexpiresAtMs\x12*\n" +
	"\x11quota_limit_bytes\x18\a \x01(\x03R\x0fquotaLimitBytes\x12@\n" +
	"\x1dlast_known_global_usage_bytes\x18\b \x01(\x03R\x19lastKnownGlobalUsageBytes\x129\n" +
	"\x19quota_guard_overage_bytes\x18\t \x01(\x03R\x16quotaGuardOverageBytes\"r\n" +
	"\x18UserAuthSnapshotResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12=\n" +
	"\tsnapshots\x18\x02 \x03(\v2\x1f.laz.nodeproto.UserAuthSnapshotR\tsnapshots\"\xa4\x01\n" +
	"\n" +
	"UsageBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\afrom_ms\x18\x03 \x01(\x03R\x06fromMs\x12\x13\n" +
	"\x05to_ms\x18\x04 \x01(\x03R\x04toMs\x124\n" +
	"\arecords\x18\x05 \x03(\v2\x1a.laz.nodeproto.UsageRecordR\arecords\"h\n" +
	"\vUsageRecord\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\x03R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x03R\arxBytes\"5\n" +
	"\bUsageAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\xa3\x03\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x126\n" +
	"\x17hysteria_service_status\x18\x04 \x01(\tR\x15hysteriaServiceStatus\x12;\n" +
	"\x1alast_traffic_collection_ms\x18\x05 \x01(\x03R\x17lastTrafficCollectionMs\x129\n" +
	"\x19last_online_collection_ms\x18\x06 \x01(\x03R\x16lastOnlineCollectionMs\x129\n" +
	"\x19pending_usage_batch_count\x18\a \x01(\x05R\x16pendingUsageBatchCount\x12B\n" +
	"\x1epending_usage_queue_size_bytes\x18\b \x01(\x03R\x1apendingUsageQueueSizeBytes\"s\n" +
	"\fOnlineReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x13\n" +
	"\x05at_ms\x18\x02 \x01(\x03R\x04atMs\x125\n" +
	"\aclients\x18\x03 \x03(\v2\x1b.laz.nodeproto.OnlineClientR\aclients\"I\n" +
	"\fOnlineClient\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xf2\x01\n" +
	"\x0eRuntimeCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tissued_ms\x18\x03 \x01(\x03R\bissuedMs\x12\x1d\n" +
	"\n" +
	"expires_ms\x18\x04 \x01(\x03R\texpiresMs\x12D\n" +
	"\apayload\x18\x05 \x03(\v2*.laz.nodeproto.RuntimeCommand.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x14RuntimeCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"u\n" +
	"\n" +
	"AgentHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\"\x92\x05\n" +
	"\fAgentMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12/\n" +
	"\x05hello\x18\x03 \x01(\v2\x19.laz.nodeproto.AgentHelloR\x05hello\x126\n" +
	"\theartbeat\x18\x04 \x01(\v2\x18.laz.nodeproto.HeartbeatR\theartbeat\x12@\n" +
	"\ronline_report\x18\x05 \x01(\v2\x1b.laz.nodeproto.OnlineReportR\fonlineReport\x12:\n" +
	"\vusage_batch\x18\x06 \x01(\v2\x19.laz.nodeproto.UsageBatchR\n" +
	"usageBatch\x12Y\n" +
	"\x16runtime_command_result\x18\a \x01(\v2#.laz.nodeproto.RuntimeCommandResultR\x14runtimeCommandResult\x12P\n" +
	"\x13auth_refresh_result\x18\b \x01(\v2 .laz.nodeproto.AuthRefreshResultR\x11authRefreshResult\x12V\n" +
	"\x15auth_manifest_request\x18\t \x01(\v2\".laz.nodeproto.AuthManifestRequestR\x13authManifestRequest\x12c\n" +
	"\x1auser_auth_snapshot_request\x18\n" +
	" \x01(\v2&.laz.nodeproto.UserAuthSnapshotRequestR\x17userAuthSnapshotRequest\"\xc2\x03\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12=\n" +
	"\fauth_refresh\x18\x03 \x01(\v2\x1a.laz.nodeproto.AuthRefreshR\vauthRefresh\x12F\n" +
	"\x0fruntime_command\x18\x04 \x01(\v2\x1d.laz.nodeproto.RuntimeCommandR\x0eruntimeCommand\x124\n" +
	"\tusage_ack\x18\x05 \x01(\v2\x17.laz.nodeproto.UsageAckR\busageAck\x12Y\n" +
	"\x16auth_manifest_response\x18\x06 \x01(\v2#.laz.nodeproto.AuthManifestResponseR\x14authManifestResponse\x12f\n" +
	"\x1buser_auth_snapshot_response\x18\a \x01(\v2'.laz.nodeproto.UserAuthSnapshotResponseR\x18userAuthSnapshotResponse\"c\n" +
	"\vAuthRefresh\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"\x93\x01\n" +
	"\x11AuthRefreshResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2X\n" +
	"\fAgentControl\x12H\n" +
	"\aConnect\x12\x1b.laz.nodeproto.AgentMessage\x1a\x1c.laz.nodeproto.ServerMessage(\x010\x01B\"Z laz/internal/nodeproto;nodeprotob\x06proto3"

var (
	file_proto_agentcontrol_proto_rawDescOnce sync.Once
	file_proto_agentcontrol_proto_rawDescData []byte
)

func file_proto_agentcontrol_proto_rawDescGZIP() []byte {
	file_proto_agentcontrol_proto_rawDescOnce.Do(func() {
		file_proto_agentcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentcontrol_proto_rawDesc), len(file_proto_agentcontrol_proto_rawDesc)))
	})
	return file_proto_agentcontrol_proto_rawDescData
}

var file_proto_agentcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_agentcontrol_proto_goTypes = []any{
	(*AuthManifestRequest)(nil),      // 0: laz.nodeproto.AuthManifestRequest
	(*AuthManifestResponse)(nil),     // 1: laz.nodeproto.AuthManifestResponse
	(*UserAuthSnapshotRequest)(nil),  // 2: laz.nodeproto.UserAuthSnapshotRequest
	(*UserAuthSnapshot)(nil),         // 3: laz.nodeproto.UserAuthSnapshot
	(*UserAuthSnapshotResponse)(nil), // 4: laz.nodeproto.UserAuthSnapshotResponse
	(*UsageBatch)(nil),               // 5: laz.nodeproto.UsageBatch
	(*UsageRecord)(nil),              // 6: laz.nodeproto.UsageRecord
	(*UsageAck)(nil),                 // 7: laz.nodeproto.UsageAck
	(*Heartbeat)(nil),                // 8: laz.nodeproto.Heartbeat
	(*OnlineReport)(nil),             // 9: laz.nodeproto.OnlineReport
	(*OnlineClient)(nil),             // 10: laz.nodeproto.OnlineClient
	(*RuntimeCommand)(nil),           // 11: laz.nodeproto.RuntimeCommand
	(*RuntimeCommandResult)(nil),     // 12: laz.nodeproto.RuntimeCommandResult
	(*AgentHello)(nil),               // 13: laz.nodeproto.AgentHello
	(*AgentMessage)(nil),             // 14: laz.nodeproto.AgentMessage
	(*ServerMessage)(nil),            // 15: laz.nodeproto.ServerMessage
	(*AuthRefresh)(nil),              // 16: laz.nodeproto.AuthRefresh
	(*AuthRefreshResult)(nil),        // 17: laz.nodeproto.AuthRefreshResult
	nil,                              // 18: laz.nodeproto.RuntimeCommand.PayloadEntry
}
var file_proto_agentcontrol_proto_depIdxs = []int32{
	3,  // 0: laz.nodeproto.UserAuthSnapshotResponse.snapshots:type_name -> laz.nodeproto.UserAuthSnapshot
	6,  // 1: laz.nodeproto.UsageBatch.records:type_name -> laz.nodeproto.UsageRecord
	10, // 2: laz.nodeproto.OnlineReport.clients:type_name -> laz.nodeproto.OnlineClient
	18, // 3: laz.nodeproto.RuntimeCommand.payload:type_name -> laz.nodeproto.RuntimeCommand.PayloadEntry
	13, // 4: laz.nodeproto.AgentMessage.hello:type_name -> laz.nodeproto.AgentHello
	8,  // 5: laz.nodeproto.AgentMessage.heartbeat:type_name -> laz.nodeproto.Heartbeat
	9,  // 6: laz.nodeproto.AgentMessage.online_report:type_name -> laz.nodeproto.OnlineReport
	5,  // 7: laz.nodeproto.AgentMessage.usage_batch:type_name -> laz.nodeproto.UsageBatch
	12, // 8: laz.nodeproto.AgentMessage.runtime_command_result:type_name -> laz.nodeproto.RuntimeCommandResult
	17, // 9: laz.nodeproto.AgentMessage.auth_refresh_result:type_name -> laz.nodeproto.AuthRefreshResult
	0,  // 10: laz.nodeproto.AgentMessage.auth_manifest_request:type_name -> laz.nodeproto.AuthManifestRequest
	2,  // 11: laz.nodeproto.AgentMessage.user_auth_snapshot_request:type_name -> laz.nodeproto.UserAuthSnapshotRequest
	16, // 12: laz.nodeproto.ServerMessage.auth_refresh:type_name -> laz.nodeproto.AuthRefresh
	11, // 13: laz.nodeproto.ServerMessage.runtime_command:type_name -> laz.nodeproto.RuntimeCommand
	7,  // 14: laz.nodeproto.ServerMessage.usage_ack:type_name -> laz.nodeproto.UsageAck
	1,  // 15: laz.nodeproto.ServerMessage.auth_manifest_response:type_name -> laz.nodeproto.AuthManifestResponse
	4,  // 16: laz.nodeproto.ServerMessage.user_auth_snapshot_response:type_name -> laz.nodeproto.UserAuthSnapshotResponse
	14, // 17: laz.nodeproto.AgentControl.Connect:input_type -> laz.nodeproto.AgentMessage
	15, // 18: laz.nodeproto.AgentControl.Connect:output_type -> laz.nodeproto.ServerMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_agentcontrol_proto_init() }
func file_proto_agentcontrol_proto_init() {
	if File_proto_agentcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentcontrol_proto_rawDesc), len(file_proto_agentcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentcontrol_proto_goTypes,
		DependencyIndexes: file_proto_agentcontrol_proto_depIdxs,
		MessageInfos:      file_proto_agentcontrol_proto_msgTypes,
	}.Build()
	File_proto_agentcontrol_proto = out.File
	file_proto_agentcontrol_proto_goTypes = nil
	file_proto_agentcontrol_proto_depIdxs = nil
}
