// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapping

import (
	model "laz/internal/model"
	record "laz/internal/storage/record"
	"time"
)

type ConverterImpl struct{}

func (c *ConverterImpl) AccessTokenModel(source record.AccessToken) model.AccessToken {
	var modelAccessToken model.AccessToken
	modelAccessToken.ID = source.ID
	modelAccessToken.AccountID = source.AccountID
	modelAccessToken.ClientID = source.ClientID
	modelAccessToken.Token = source.Token
	modelAccessToken.TokenHash = source.TokenHash
	modelAccessToken.Purpose = source.Purpose
	modelAccessToken.Status = model.Status(source.Status)
	modelAccessToken.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	modelAccessToken.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	modelAccessToken.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelAccessToken.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelAccessToken
}
func (c *ConverterImpl) AccessTokenRecord(source model.AccessToken) record.AccessToken {
	var recordAccessToken record.AccessToken
	recordAccessToken.ID = source.ID
	recordAccessToken.AccountID = source.AccountID
	recordAccessToken.ClientID = source.ClientID
	recordAccessToken.Token = source.Token
	recordAccessToken.TokenHash = source.TokenHash
	recordAccessToken.Purpose = source.Purpose
	recordAccessToken.Status = string(source.Status)
	recordAccessToken.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	recordAccessToken.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	recordAccessToken.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordAccessToken.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordAccessToken
}
func (c *ConverterImpl) AccountModel(source record.Account) model.Account {
	var modelAccount model.Account
	modelAccount.ID = source.ID
	modelAccount.Username = source.Username
	modelAccount.DisplayName = source.DisplayName
	modelAccount.Status = model.Status(source.Status)
	modelAccount.Note = source.Note
	modelAccount.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelAccount.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelAccount
}
func (c *ConverterImpl) AccountPolicyTagModel(source record.AccountPolicyTag) model.AccountPolicyTag {
	var modelAccountPolicyTag model.AccountPolicyTag
	modelAccountPolicyTag.ID = source.ID
	modelAccountPolicyTag.AccountID = source.AccountID
	modelAccountPolicyTag.TagID = source.TagID
	modelAccountPolicyTag.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	return modelAccountPolicyTag
}
func (c *ConverterImpl) AccountPolicyTagRecord(source model.AccountPolicyTag) record.AccountPolicyTag {
	var recordAccountPolicyTag record.AccountPolicyTag
	recordAccountPolicyTag.ID = source.ID
	recordAccountPolicyTag.AccountID = source.AccountID
	recordAccountPolicyTag.TagID = source.TagID
	recordAccountPolicyTag.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	return recordAccountPolicyTag
}
func (c *ConverterImpl) AccountRecord(source model.Account) record.Account {
	var recordAccount record.Account
	recordAccount.ID = source.ID
	recordAccount.Username = source.Username
	recordAccount.DisplayName = source.DisplayName
	recordAccount.Status = string(source.Status)
	recordAccount.Note = source.Note
	recordAccount.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordAccount.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordAccount
}
func (c *ConverterImpl) AdminSessionModel(source record.AdminSession) model.AdminSession {
	var modelAdminSession model.AdminSession
	modelAdminSession.ID = source.ID
	modelAdminSession.Token = source.Token
	modelAdminSession.TokenHash = source.TokenHash
	modelAdminSession.CSRFToken = source.CSRFToken
	modelAdminSession.CSRFTokenHash = source.CSRFTokenHash
	modelAdminSession.PrincipalName = source.PrincipalName
	modelAdminSession.Role = source.Role
	modelAdminSession.Status = model.Status(source.Status)
	modelAdminSession.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	modelAdminSession.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	modelAdminSession.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelAdminSession.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelAdminSession
}
func (c *ConverterImpl) AdminSessionRecord(source model.AdminSession) record.AdminSession {
	var recordAdminSession record.AdminSession
	recordAdminSession.ID = source.ID
	recordAdminSession.Token = source.Token
	recordAdminSession.TokenHash = source.TokenHash
	recordAdminSession.CSRFToken = source.CSRFToken
	recordAdminSession.CSRFTokenHash = source.CSRFTokenHash
	recordAdminSession.PrincipalName = source.PrincipalName
	recordAdminSession.Role = source.Role
	recordAdminSession.Status = string(source.Status)
	recordAdminSession.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	recordAdminSession.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	recordAdminSession.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordAdminSession.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordAdminSession
}
func (c *ConverterImpl) AuditLogModel(source record.AuditLog) model.AuditLog {
	var modelAuditLog model.AuditLog
	modelAuditLog.ID = source.ID
	modelAuditLog.Actor = source.Actor
	modelAuditLog.Action = source.Action
	modelAuditLog.EntityType = source.EntityType
	modelAuditLog.EntityID = source.EntityID
	modelAuditLog.Details = source.Details
	modelAuditLog.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	return modelAuditLog
}
func (c *ConverterImpl) AuditLogRecord(source model.AuditLog) record.AuditLog {
	var recordAuditLog record.AuditLog
	recordAuditLog.ID = source.ID
	recordAuditLog.Actor = source.Actor
	recordAuditLog.Action = source.Action
	recordAuditLog.EntityType = source.EntityType
	recordAuditLog.EntityID = source.EntityID
	recordAuditLog.Details = source.Details
	recordAuditLog.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	return recordAuditLog
}
func (c *ConverterImpl) ClientCredentialModel(source record.ClientCredential) model.ClientCredential {
	var modelClientCredential model.ClientCredential
	modelClientCredential.AccountID = source.AccountID
	modelClientCredential.PINHash = source.PINHash
	modelClientCredential.RecoveryCodeHash = source.RecoveryCodeHash
	modelClientCredential.FailedAttempts = source.FailedAttempts
	modelClientCredential.LockedUntil = c.timeTimeToTimeTime(source.LockedUntil)
	modelClientCredential.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelClientCredential.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelClientCredential
}
func (c *ConverterImpl) ClientCredentialRecord(source model.ClientCredential) record.ClientCredential {
	var recordClientCredential record.ClientCredential
	recordClientCredential.AccountID = source.AccountID
	recordClientCredential.PINHash = source.PINHash
	recordClientCredential.RecoveryCodeHash = source.RecoveryCodeHash
	recordClientCredential.FailedAttempts = source.FailedAttempts
	recordClientCredential.LockedUntil = c.timeTimeToTimeTime(source.LockedUntil)
	recordClientCredential.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordClientCredential.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordClientCredential
}
func (c *ConverterImpl) ClientModel(source record.Client) model.Client {
	var modelClient model.Client
	modelClient.ID = source.ID
	modelClient.AccountID = source.AccountID
	modelClient.Slug = source.Slug
	modelClient.Name = source.Name
	modelClient.Status = model.Status(source.Status)
	modelClient.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelClient.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelClient
}
func (c *ConverterImpl) ClientRecord(source model.Client) record.Client {
	var recordClient record.Client
	recordClient.ID = source.ID
	recordClient.AccountID = source.AccountID
	recordClient.Slug = source.Slug
	recordClient.Name = source.Name
	recordClient.Status = string(source.Status)
	recordClient.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordClient.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordClient
}
func (c *ConverterImpl) ClientSessionModel(source record.ClientSession) model.ClientSession {
	var modelClientSession model.ClientSession
	modelClientSession.ID = source.ID
	modelClientSession.AccountID = source.AccountID
	modelClientSession.Token = source.Token
	modelClientSession.TokenHash = source.TokenHash
	modelClientSession.Status = model.Status(source.Status)
	modelClientSession.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	modelClientSession.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	modelClientSession.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelClientSession.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelClientSession
}
func (c *ConverterImpl) ClientSessionRecord(source model.ClientSession) record.ClientSession {
	var recordClientSession record.ClientSession
	recordClientSession.ID = source.ID
	recordClientSession.AccountID = source.AccountID
	recordClientSession.Token = source.Token
	recordClientSession.TokenHash = source.TokenHash
	recordClientSession.Status = string(source.Status)
	recordClientSession.ExpiresAt = c.timeTimeToTimeTime(source.ExpiresAt)
	recordClientSession.LastUsedAt = c.timeTimeToTimeTime(source.LastUsedAt)
	recordClientSession.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordClientSession.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordClientSession
}
func (c *ConverterImpl) ConfigProfileModel(source record.ConfigProfile) model.ConfigProfile {
	var modelConfigProfile model.ConfigProfile
	modelConfigProfile.ID = source.ID
	modelConfigProfile.Protocol = model.Protocol(source.Protocol)
	modelConfigProfile.Kind = model.ConfigKind(source.Kind)
	modelConfigProfile.Slug = source.Slug
	modelConfigProfile.Name = source.Name
	modelConfigProfile.Client = source.Client
	modelConfigProfile.ContentType = source.ContentType
	modelConfigProfile.ConfigTemplate = source.ConfigTemplate
	modelConfigProfile.Status = model.Status(source.Status)
	modelConfigProfile.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelConfigProfile.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelConfigProfile
}
func (c *ConverterImpl) ConfigProfileRecord(source model.ConfigProfile) record.ConfigProfile {
	var recordConfigProfile record.ConfigProfile
	recordConfigProfile.ID = source.ID
	recordConfigProfile.Protocol = string(source.Protocol)
	recordConfigProfile.Kind = string(source.Kind)
	recordConfigProfile.Slug = source.Slug
	recordConfigProfile.Name = source.Name
	recordConfigProfile.Client = source.Client
	recordConfigProfile.ContentType = source.ContentType
	recordConfigProfile.ConfigTemplate = source.ConfigTemplate
	recordConfigProfile.Status = string(source.Status)
	recordConfigProfile.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordConfigProfile.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordConfigProfile
}
func (c *ConverterImpl) ConnectionModel(source record.Connection) model.Connection {
	var modelConnection model.Connection
	modelConnection.ID = source.ID
	modelConnection.AccountID = source.AccountID
	modelConnection.ClientID = source.ClientID
	modelConnection.NodeID = source.NodeID
	modelConnection.Protocol = model.Protocol(source.Protocol)
	modelConnection.RemoteID = source.RemoteID
	modelConnection.RemoteName = source.RemoteName
	modelConnection.Status = model.Status(source.Status)
	modelConnection.DesiredStatus = model.Status(source.DesiredStatus)
	modelConnection.LastSyncAt = c.timeTimeToTimeTime(source.LastSyncAt)
	modelConnection.LastError = source.LastError
	modelConnection.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelConnection.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelConnection
}
func (c *ConverterImpl) ConnectionRecord(source model.Connection) record.Connection {
	var recordConnection record.Connection
	recordConnection.ID = source.ID
	recordConnection.AccountID = source.AccountID
	recordConnection.ClientID = source.ClientID
	recordConnection.NodeID = source.NodeID
	recordConnection.Protocol = string(source.Protocol)
	recordConnection.RemoteID = source.RemoteID
	recordConnection.RemoteName = source.RemoteName
	recordConnection.Status = c.modelStatusToString(source.Status)
	recordConnection.DesiredStatus = c.modelStatusToString(source.DesiredStatus)
	recordConnection.LastSyncAt = c.timeTimeToTimeTime(source.LastSyncAt)
	recordConnection.LastError = source.LastError
	recordConnection.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordConnection.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordConnection
}
func (c *ConverterImpl) IssuedConfigModel(source record.IssuedConfig) model.IssuedConfig {
	var modelIssuedConfig model.IssuedConfig
	modelIssuedConfig.ID = source.ID
	modelIssuedConfig.ConnectionID = source.ConnectionID
	modelIssuedConfig.Kind = model.ConfigKind(source.Kind)
	modelIssuedConfig.Slug = source.Slug
	modelIssuedConfig.Name = source.Name
	modelIssuedConfig.Client = source.Client
	modelIssuedConfig.ContentType = source.ContentType
	modelIssuedConfig.Config = source.Config
	modelIssuedConfig.Status = model.Status(source.Status)
	modelIssuedConfig.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelIssuedConfig.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelIssuedConfig
}
func (c *ConverterImpl) IssuedConfigRecord(source model.IssuedConfig) record.IssuedConfig {
	var recordIssuedConfig record.IssuedConfig
	recordIssuedConfig.ID = source.ID
	recordIssuedConfig.ConnectionID = source.ConnectionID
	recordIssuedConfig.Kind = string(source.Kind)
	recordIssuedConfig.Slug = source.Slug
	recordIssuedConfig.Name = source.Name
	recordIssuedConfig.Client = source.Client
	recordIssuedConfig.ContentType = source.ContentType
	recordIssuedConfig.Config = source.Config
	recordIssuedConfig.Status = c.modelStatusToString(source.Status)
	recordIssuedConfig.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordIssuedConfig.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordIssuedConfig
}
func (c *ConverterImpl) NodeModel(source record.Node) model.Node {
	var modelNode model.Node
	modelNode.ID = source.ID
	modelNode.Name = source.Name
	modelNode.Type = model.NodeType(source.Type)
	modelNode.BaseURL = source.BaseURL
	modelNode.APIKey = source.APIKey
	modelNode.Region = source.Region
	modelNode.SSHHost = source.SSHHost
	modelNode.SSHPort = source.SSHPort
	modelNode.SSHUser = source.SSHUser
	modelNode.SSHKeyPath = source.SSHKeyPath
	modelNode.UseIPv6 = source.UseIPv6
	modelNode.Status = model.Status(source.Status)
	modelNode.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelNode.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelNode
}
func (c *ConverterImpl) NodeRecord(source model.Node) record.Node {
	var recordNode record.Node
	recordNode.ID = source.ID
	recordNode.Name = source.Name
	recordNode.Type = string(source.Type)
	recordNode.BaseURL = source.BaseURL
	recordNode.APIKey = source.APIKey
	recordNode.Region = source.Region
	recordNode.SSHHost = source.SSHHost
	recordNode.SSHPort = source.SSHPort
	recordNode.SSHUser = source.SSHUser
	recordNode.SSHKeyPath = source.SSHKeyPath
	recordNode.UseIPv6 = source.UseIPv6
	recordNode.Status = c.modelStatusToString(source.Status)
	recordNode.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordNode.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordNode
}
func (c *ConverterImpl) PolicyTagModel(source record.PolicyTag) model.PolicyTag {
	var modelPolicyTag model.PolicyTag
	modelPolicyTag.ID = source.ID
	modelPolicyTag.Slug = source.Slug
	modelPolicyTag.Name = source.Name
	modelPolicyTag.AllowedNodeIDs = source.AllowedNodeIDs
	modelPolicyTag.ClientLimit = source.ClientLimit
	modelPolicyTag.Status = model.Status(source.Status)
	modelPolicyTag.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelPolicyTag.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelPolicyTag
}
func (c *ConverterImpl) PolicyTagRecord(source model.PolicyTag) record.PolicyTag {
	var recordPolicyTag record.PolicyTag
	recordPolicyTag.ID = source.ID
	recordPolicyTag.Slug = source.Slug
	recordPolicyTag.Name = source.Name
	recordPolicyTag.AllowedNodeIDs = source.AllowedNodeIDs
	recordPolicyTag.ClientLimit = source.ClientLimit
	recordPolicyTag.Status = c.modelStatusToString(source.Status)
	recordPolicyTag.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordPolicyTag.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordPolicyTag
}
func (c *ConverterImpl) ShortLinkModel(source record.ShortLink) model.ShortLink {
	var modelShortLink model.ShortLink
	modelShortLink.ID = source.ID
	modelShortLink.TokenID = source.TokenID
	modelShortLink.Profile = source.Profile
	modelShortLink.TargetURL = source.TargetURL
	modelShortLink.EncryptedURL = source.EncryptedURL
	modelShortLink.Status = model.Status(source.Status)
	modelShortLink.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	modelShortLink.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return modelShortLink
}
func (c *ConverterImpl) ShortLinkRecord(source model.ShortLink) record.ShortLink {
	var recordShortLink record.ShortLink
	recordShortLink.ID = source.ID
	recordShortLink.TokenID = source.TokenID
	recordShortLink.Profile = source.Profile
	recordShortLink.TargetURL = source.TargetURL
	recordShortLink.EncryptedURL = source.EncryptedURL
	recordShortLink.Status = c.modelStatusToString(source.Status)
	recordShortLink.CreatedAt = c.timeTimeToTimeTime(source.CreatedAt)
	recordShortLink.UpdatedAt = c.timeTimeToTimeTime(source.UpdatedAt)
	return recordShortLink
}
func (c *ConverterImpl) modelStatusToString(source model.Status) string {
	return string(source)
}
func (c *ConverterImpl) timeTimeToTimeTime(source time.Time) time.Time {
	return source
}
